import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {

  let [vals, setVals] = useState({

    days: '0',
    hours: '0',
    mins: '0',
    secs: '0',


  });

  useEffect(() => {
    let t = (setInterval(() => {
      // let bday = new Date(1999,7,14);
      let cday = new Date(2029, 7, 14);

      let diff = cday.getTime() - new Date().getTime();
      const days = Math.floor(diff / (1000 * 60 * 60 * 24));
      let remainder = diff % (1000 * 60 * 60 * 24);

      const hours = Math.floor(remainder / (1000 * 60 * 60));
      remainder = diff % (1000 * 60 * 60);

      const mins = Math.floor(remainder / (1000 * 60));
      remainder = diff % (1000 * 60);
      const secs = Math.floor(remainder / (1000));

      setVals({
        days: days.toString(),
        hours: hours.toString(),
        mins: mins.toString(),
        secs: secs.toString().padStart(2, '0'),
      });
    }, 1000));
    return () => clearInterval(t);
  }, []);

  return (
    <div className={styles.container}>
      <div className={styles.bg}>
        <Image src={require("../public/bg.png")} className={styles.bgimg} width={2000} height={2000} layout="fill" objectFit="cover" />
        <div className={styles.gridOverlay} />
      </div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.values}>
          <h2 key={1} className={styles.title}>
            {vals.days} Days
          </h2>
          <h2 key={2} className={styles.title}>
            {vals.hours} Hours
          </h2>
          <h2 key={3} className={styles.title}>
            {vals.mins} Minutes
          </h2>
          <h2 key={4} className={styles.title}>
            {vals.secs} Seconds
          </h2>

        </div>

      </main>
    </div>
  )
}

export default Home
